version: "2.3"
services:
  local_debug:
    build: ..
    volumes:
      - ./:/recipes
      - ../work:/work
      - ../work/data:/work/data
      - ../neuralpredictors:/src/neuralpredictors
      - ../nnfabrik:/src/nnfabrik
      - ../nnvision:/src/nnvision
      - ../neural_cotraining:/src/neural_cotraining
      - ../nntransfer:/src/nntransfer
      - /tmp/djcache:/cache
    env_file: .env
    working_dir: /recipes/
    entrypoint: ""
  local_develop:
    build: ..
    volumes:
      - ./:/recipes
      - ../work:/work
      - ../work/data:/work/data
      - ../neuralpredictors:/src/neuralpredictors
      - ../nnfabrik:/src/nnfabrik
      - ../nnvision:/src/nnvision
      - ../neural_cotraining:/src/neural_cotraining
      - ../nntransfer:/src/nntransfer
      - /tmp/djcache:/cache
    working_dir: /recipes/
    ports:
      - "8888:8888"
    env_file: .env
  tpu_develop:
    build: ..
    volumes:
      - ./:/recipes
      - ../work:/work
      - ../work/data:/work/data
      - ../neuralpredictors:/src/neuralpredictors
      - ../nnfabrik:/src/nnfabrik
      - ../nnvision:/src/nnvision
      - ../neural_cotraining:/src/neural_cotraining
      - ../nntransfer:/src/nntransfer
      - /tmp/djcache:/cache
    working_dir: /recipes/
    env_file: .env
    environment:
      - TPU_IP_ADDRESS
    ipc: host
    shm_size: 16g
  tpu_job:
    build:
      context: ..
      dockerfile: TPUDockerfile
    volumes:
      - ./:/recipes
      - ../work:/work
      - ../work/data:/work/data
      - ../neuralpredictors:/src/neuralpredictors
      - ../nnfabrik:/src/nnfabrik
      - ../nnvision:/src/nnvision
      - ../neural_cotraining:/src/neural_cotraining
      - ../nntransfer:/src/nntransfer
      - /tmp/djcache:/cache
    env_file: .env
    environment:
      - TPU_IP_ADDRESS
    entrypoint: ""
    working_dir: /recipes/
    command: main.py
    ipc: host
    shm_size: 16g
  server_develop:
    build: ..
    volumes:
      - ./:/recipes
      - ../:/misc
      - ../work:/work
      - ../neuralpredictors:/src/neuralpredictors
      - ../nnfabrik:/src/nnfabrik
      - ../nnvision:/src/nnvision
      - ../neural_cotraining:/src/neural_cotraining
      - ../nntransfer:/src/nntransfer
      - /tmp/djcache:/cache
    working_dir: /recipes/
    env_file: .env
    runtime: nvidia
    ipc: host
    shm_size: 40g
  server_analysis:
    build: ..
    volumes:
      - ./:/recipes
      - ../work:/work
      - ../work/data:/work/data
      - ../neuralpredictors:/src/neuralpredictors
      - ../nnfabrik:/src/nnfabrik
      - ../nnvision:/src/nnvision
      - ../neural_cotraining:/src/neural_cotraining
      - ../nntransfer:/src/nntransfer
      - /tmp/djcache:/cache
    env_file: .env
    runtime: nvidia
    entrypoint: python3
    working_dir: /recipes/
    command: main.py
    ipc: host
    shm_size: 40g
  server_job:
    build: ..
    volumes:
      - ./:/recipes
      - ../work:/work
      - ../work/data:/work/data
      - ../neuralpredictors:/src/neuralpredictors
      - ../nnfabrik:/src/nnfabrik
      - ../nnvision:/src/nnvision
      - ../neural_cotraining:/src/neural_cotraining
      - ../nntransfer:/src/nntransfer
      - /tmp/djcache:/cache
    env_file: .env
    runtime: nvidia
    entrypoint: python3
    working_dir: /recipes/
    command: main.py
    ipc: host
    shm_size: 40g
  server_run_tests:
    build: ..
    volumes:
      - ./:/recipes
      - ../work:/work
      - ../work/data:/work/data
      - ../neuralpredictors:/src/neuralpredictors
      - ../nnfabrik:/src/nnfabrik
      - ../nnvision:/src/nnvision
      - ../neural_cotraining:/src/neural_cotraining
      - ../nntransfer:/src/nntransfer
      - /tmp/djcache:/cache
    env_file: .env
    runtime: nvidia
    entrypoint: ""
    working_dir: /src/neural_cotraining/neural_cotraining
    command: ./run_tests.sh
    ipc: host
    shm_size: 40g


